<?php
namespace AppBundle\Repository;
/**
 * FaceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}